server:
  port: 8000

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/seat?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: inno.server.sw1.seatlottery.mapper